# Generated by Django 3.2.9 on 2021-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
