# Generated by Django 3.2.9 on 2021-12-04 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20211204_2205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0002_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamposition',
            name='required_positions',
        ),
        migrations.AddField(
            model_name='teamposition',
            name='required_positions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_positions', to='recommend.position'),
        ),
        migrations.AlterField(
            model_name='teamposition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_positions', to=settings.AUTH_USER_MODEL),
        ),
    ]
