# Generated by Django 3.2.9 on 2021-12-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211204_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='subject',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
