# Generated by Django 3.2.9 on 2021-12-04 13:48

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=None, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='at-hackathon'), upload_to='profile/image/'),
            preserve_default=False,
        ),
    ]
