# Generated by Django 3.2.9 on 2021-12-04 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Link'), (2, 'Text')])),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('portfolios', models.ManyToManyField(related_name='profiles', to='portfolio.Portfolio')),
            ],
        ),
    ]
