# Generated by Django 3.2.9 on 2021-12-04 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.IntegerField(choices=[(1, '남성'), (2, '여성'), (3, '기타')])),
                ('school', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
