# Generated by Django 3.2.9 on 2021-12-04 08:47

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(default=None, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='at-hackathon'), upload_to='profile/document/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='group_category1_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='group_category2_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='group_category3_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=None, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='at-hackathon'), upload_to='profile/image/'),
            preserve_default=False,
        ),
    ]
