# Generated by Django 3.2.9 on 2021-12-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211204_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio',
            field=models.TextField(blank=True),
        ),
    ]
