# Generated by Django 3.2.9 on 2021-12-04 18:12

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211205_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='at-hackathon'), upload_to='profile/document/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='at-hackathon'), upload_to='profile/image/'),
        ),
    ]
